version: "3"
services:
    express:
        build: server
        ports: 
            - "3000:3000"
        volumes: 
            - ./server:/usr/src/app/
            - /usr/src/app/node_modules
    angular:
        build: Bingo
        ports:
            - "9000:4200"
        volumes: 
            - ./Bingo:/usr/src/app
            - /usr/src/app/node_modules 
        links: 
            - express