version: "3"
services:
    angular:
        build: .
        ports:
            # - "9000:80"
            - "9000:4200"
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules 