FROM node:14.2.0-alpine3.11 as build

WORKDIR /usr/src/app

COPY . ./

RUN npm install --quiet
RUN npm run build

FROM node:14.2.0-alpine3.11 as work

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --prod --quiet
COPY --from=build /usr/src/app/dist/ .
EXPOSE 3000

CMD ["npm", "start"]